### ISSUE TITLE
安装fresh失败

### ISSUE THREAD

**Issue by jiyindaohanli** [Away0x/gin_weibo#2]
```
# unicode/utf8
compile: version "go1.10.3" does not match go tool version "go1.12.6"
# unicode
compile: version "go1.10.3" does not match go tool version "go1.12.6"
# internal/nettrace
compile: version "go1.10.3" does not match go tool version "go1.12.6"

```

**Comment by Away0x** [comment]
> ```
> # unicode/utf8
> compile: version "go1.10.3" does not match go tool version "go1.12.6"
> # unicode
> compile: version "go1.10.3" does not match go tool version "go1.12.6"
> # internal/nettrace
> compile: version "go1.10.3" does not match go tool version "go1.12.6"
> ```

需要升级一下 go 的版本
